_unit = _this select 0;

comment "Remove existing items";
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;

comment "Add weapons";
_unit addWeapon "BWA3_G36KA4";
_unit addPrimaryWeaponItem "BWA3_acc_LLM01_irlaser";
_unit addPrimaryWeaponItem "BWA3_optic_EOTech552";
_unit addPrimaryWeaponItem "BWA3_30Rnd_556x45_G36";
_unit addPrimaryWeaponItem "BWA3_bipod_Harris";
_unit addWeapon "BWA3_P8";
_unit addHandgunItem "BWA3_acc_LLM01_irlaser";
_unit addHandgunItem "BWA3_15Rnd_9x19_P8";

comment "Add containers";
_unit forceAddUniform "CryeGen3_Uniform_FlecktarnWoodland";
_unit addVest "KSK_PlateCarrier2_FlecktarnDW_Assault";
_unit addBackpack "BWA3_PatrolPack_Fleck";

comment "Add binoculars";
_unit addWeapon "ACE_Vector";

comment "Add items to containers";
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_elasticBandage";};
_unit addItemToUniform "BW_Facepaint";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_epinephrine";};
_unit addItemToUniform "ACE_IR_Strobe_Item";
for "_i" from 1 to 3 do {_unit addItemToUniform "ACE_CableTie";};
_unit addItemToUniform "ACE_MapTools";
_unit addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_morphine";};
_unit addItemToUniform "KNB_Notebook";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_EarPlugs";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_tourniquet";};
_unit addItemToUniform "ACE_microDAGR";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_Chemlight_HiWhite";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_Chemlight_HiGreen";};
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_fieldDressing";};
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_elasticBandage";};
_unit addItemToVest "ACE_EntrenchingTool";
_unit addItemToVest "ACE_Chemlight_Shield";
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_packingBandage";};
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_quikclot";};
_unit addItemToVest "BWA3_optic_ZO4x30i_MicroT2";
_unit addItemToVest "SMA_eotechG33_3XDOWN";
_unit addItemToVest "BWA3_muzzle_snds_QDSS";
_unit addItemToVest "ACRE_PRC152";
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_Chemlight_HiWhite";};
for "_i" from 1 to 2 do {_unit addItemToVest "ACE_Chemlight_HiGreen";};
for "_i" from 1 to 7 do {_unit addItemToVest "BWA3_DM25";};
for "_i" from 1 to 2 do {_unit addItemToVest "BWA3_DM51A1";};
_unit addItemToVest "B_IR_Grenade";
for "_i" from 1 to 2 do {_unit addItemToVest "ACE_M84";};
for "_i" from 1 to 3 do {_unit addItemToVest "Chemlight_blue";};
for "_i" from 1 to 3 do {_unit addItemToVest "ACE_Chemlight_HiBlue";};
_unit addItemToVest "BWA3_DM32_Purple";
for "_i" from 1 to 3 do {_unit addItemToVest "BWA3_15Rnd_9x19_P8";};
for "_i" from 1 to 9 do {_unit addItemToVest "BWA3_30Rnd_556x45_G36";};
_unit addItemToVest "BWA3_DM32_Orange";
for "_i" from 1 to 3 do {_unit addItemToVest "ACE_Chemlight_IR";};
_unit addItemToBackpack "rhs_weap_m32";
for "_i" from 1 to 3 do {_unit addItemToBackpack "rhsusf_mag_6Rnd_M714_white";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "rhsusf_mag_6Rnd_M441_HE";};
_unit addHeadgear "KSK_PLAIN_2";
_unit addGoggles "Balaclava_Black_Gsg9";

comment "Add items";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ACE_Altimeter";
_unit linkItem "ACE_GD300_b";
_unit linkItem "JAS_GPNVG18_Tan";