_unit = _this select 0;

comment "Remove existing items";
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;

comment "Add weapons";
_unit addWeapon "hlc_smg_mp5k_PDW";
_unit addPrimaryWeaponItem "muzzle_snds_L";
_unit addPrimaryWeaponItem "BWA3_optic_MicroT2";
_unit addPrimaryWeaponItem "hlc_30Rnd_9x19_B_MP5";
_unit addWeapon "BWA3_P2A1";
_unit addHandgunItem "BWA3_1Rnd_Flare_Illum";

comment "Add containers";
_unit forceAddUniform "BWA3_Uniform_Helipilot";
_unit addVest "FIR_pilot_vest";
_unit addBackpack "BWA3_Kitbag_Fleck";

comment "Add binoculars";
_unit addWeapon "ACE_Vector";

comment "Add items to containers";
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_elasticBandage";};
_unit addItemToUniform "BW_Facepaint";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_epinephrine";};
_unit addItemToUniform "ACE_IR_Strobe_Item";
for "_i" from 1 to 3 do {_unit addItemToUniform "ACE_CableTie";};
_unit addItemToUniform "ACE_MapTools";
_unit addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_morphine";};
_unit addItemToUniform "KNB_Notebook";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_EarPlugs";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_tourniquet";};
_unit addItemToUniform "ACE_microDAGR";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_Chemlight_HiWhite";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_Chemlight_HiGreen";};
for "_i" from 1 to 2 do {_unit addItemToUniform "BWA3_DM32_Orange";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_Chemlight_IR";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_M84";};
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_fieldDressing";};
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_elasticBandage";};
_unit addItemToVest "ACE_EntrenchingTool";
_unit addItemToVest "ACE_Chemlight_Shield";
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_packingBandage";};
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_quikclot";};
_unit addItemToVest "ACRE_PRC152";
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_Chemlight_HiWhite";};
for "_i" from 1 to 2 do {_unit addItemToVest "ACE_Chemlight_HiGreen";};
for "_i" from 1 to 7 do {_unit addItemToVest "BWA3_DM25";};
for "_i" from 1 to 2 do {_unit addItemToVest "BWA3_DM51A1";};
_unit addItemToVest "B_IR_Grenade";
for "_i" from 1 to 3 do {_unit addItemToVest "Chemlight_blue";};
for "_i" from 1 to 3 do {_unit addItemToVest "ACE_Chemlight_HiBlue";};
_unit addItemToVest "BWA3_DM32_Purple";
_unit addItemToVest "ACE_Chemlight_IR";
_unit addItemToBackpack "rhs_beanie_green";
for "_i" from 1 to 8 do {_unit addItemToBackpack "BWA3_1Rnd_Flare_Illum";};
for "_i" from 1 to 6 do {_unit addItemToBackpack "BWA3_1Rnd_Flare_Singlestar_White";};
for "_i" from 1 to 8 do {_unit addItemToBackpack "BWA3_1Rnd_Flare_Singlestar_Green";};
for "_i" from 1 to 6 do {_unit addItemToBackpack "BWA3_1Rnd_Flare_Multistar_White";};
for "_i" from 1 to 8 do {_unit addItemToBackpack "BWA3_1Rnd_Flare_Multistar_Green";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "B_IR_Grenade";};
for "_i" from 1 to 5 do {_unit addItemToBackpack "Chemlight_green";};
for "_i" from 1 to 19 do {_unit addItemToBackpack "ACE_Chemlight_HiWhite";};
for "_i" from 1 to 10 do {_unit addItemToBackpack "hlc_30Rnd_9x19_B_MP5";};
for "_i" from 1 to 3 do {_unit addItemToBackpack "ACE_HandFlare_Green";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "BWA3_DM32_Orange";};
_unit addItemToBackpack "ACE_M14";
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_Chemlight_IR";};
_unit addHeadgear "BWA3_Knighthelm";
_unit addGoggles "G_Bandanna_blk";

comment "Add items";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ACE_Altimeter";
_unit linkItem "ACE_GD300_b";