_unit = _this select 0;

comment "Remove existing items";
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;

comment "Add weapons";
_unit addWeapon "BWA3_G29";
_unit addPrimaryWeaponItem "BWA3_muzzle_snds_Rotex_Monoblock";
_unit addPrimaryWeaponItem "BWA3_acc_VarioRay_irlaser_black";
_unit addPrimaryWeaponItem "BWA3_10Rnd_86x70_G29";
_unit addPrimaryWeaponItem "BWA3_bipod_Atlas";
_unit addWeapon "RH_g18";
_unit addHandgunItem "RH_gemtech9";
_unit addHandgunItem "RH_X300";
_unit addHandgunItem "RH_33Rnd_9x19_g18";

comment "Add containers";
_unit forceAddUniform "U_B_FullGhillie_lsh";
_unit addVest "V_Chestrig_khk";
_unit addBackpack "B_Rangemaster_belt_CTRG_004";

comment "Add binoculars";
_unit addWeapon "ACE_Vector";

comment "Add items to containers";
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 5 do {_unit addItemToUniform "ACE_elasticBandage";};
_unit addItemToUniform "BW_Facepaint";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_epinephrine";};
_unit addItemToUniform "ACE_IR_Strobe_Item";
for "_i" from 1 to 3 do {_unit addItemToUniform "ACE_CableTie";};
_unit addItemToUniform "ACE_MapTools";
_unit addItemToUniform "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_morphine";};
_unit addItemToUniform "KNB_Notebook";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_EarPlugs";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_tourniquet";};
_unit addItemToUniform "ACE_microDAGR";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_Chemlight_HiWhite";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_Chemlight_HiGreen";};
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_fieldDressing";};
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_elasticBandage";};
_unit addItemToVest "ACE_EntrenchingTool";
_unit addItemToVest "ACE_Chemlight_Shield";
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_packingBandage";};
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_quikclot";};
_unit addItemToVest "ACRE_PRC152";
for "_i" from 1 to 5 do {_unit addItemToVest "ACE_Chemlight_HiWhite";};
for "_i" from 1 to 2 do {_unit addItemToVest "ACE_Chemlight_HiGreen";};
for "_i" from 1 to 7 do {_unit addItemToVest "BWA3_DM25";};
for "_i" from 1 to 2 do {_unit addItemToVest "BWA3_DM51A1";};
_unit addItemToVest "B_IR_Grenade";
for "_i" from 1 to 2 do {_unit addItemToVest "ACE_M84";};
for "_i" from 1 to 3 do {_unit addItemToVest "Chemlight_blue";};
for "_i" from 1 to 3 do {_unit addItemToVest "ACE_Chemlight_HiBlue";};
_unit addItemToVest "BWA3_DM32_Purple";
_unit addItemToVest "BWA3_DM32_Orange";
for "_i" from 1 to 3 do {_unit addItemToVest "ACE_Chemlight_IR";};
_unit addItemToBackpack "ACE_ATragMX";
_unit addItemToBackpack "ACE_DAGR";
_unit addItemToBackpack "ACE_RangeCard";
_unit addItemToBackpack "ACE_Kestrel4500";
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_Chemlight_Shield";};
_unit addItemToBackpack "ACE_Tripod";
_unit addItemToBackpack "ACE_SpottingScope";
_unit addItemToBackpack "ACRE_VHF30108MAST";
_unit addItemToBackpack "BWA3_optic_M5Xi_Tremor3_MicroT2";
for "_i" from 1 to 2 do {_unit addItemToBackpack "SmokeShell_Cluster_Full";};
for "_i" from 1 to 3 do {_unit addItemToBackpack "ACE_Chemlight_HiBlue";};
_unit addItemToBackpack "BWA3_DM32_Purple";
for "_i" from 1 to 2 do {_unit addItemToBackpack "BWA3_DM32_Orange";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "B_IR_Grenade";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "ACE_Chemlight_HiWhite";};
for "_i" from 1 to 5 do {_unit addItemToBackpack "Chemlight_blue";};
for "_i" from 1 to 5 do {_unit addItemToBackpack "RH_33Rnd_9x19_g18";};
for "_i" from 1 to 18 do {_unit addItemToBackpack "BWA3_10Rnd_86x70_G29";};
_unit addHeadgear "TBW_booniehat_hs_Tropen";
_unit addGoggles "Balaclava_Crocodile_Gsg9";

comment "Add items";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ACE_Altimeter";
_unit linkItem "ACE_GD300_b";
_unit linkItem "JAS_GPNVG18_Tan";